# Generated by Django 3.1.7 on 2021-03-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('open', models.DateField(null=True)),
                ('close', models.DateField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('face_value', models.CharField(max_length=50, null=True)),
                ('ipo_price', models.CharField(max_length=50, null=True)),
                ('market_lot', models.CharField(max_length=50, null=True)),
                ('listing_at', models.CharField(max_length=50, null=True)),
                ('issue_size', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(default='mainboard', max_length=10, null=True)),
            ],
            options={
                'ordering': ['-open'],
            },
        ),
        migrations.CreateModel(
            name='TentativeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_of_allotment', models.DateField(null=True)),
                ('initiation_date', models.DateField(null=True)),
                ('credit_date', models.DateField(null=True)),
                ('listing_date', models.DateField(null=True)),
                ('tentative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.ipodetails')),
            ],
        ),
        migrations.CreateModel(
            name='ShareOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qib_share', models.CharField(max_length=20, null=True)),
                ('nii_share', models.CharField(max_length=20, null=True)),
                ('retail_share', models.CharField(max_length=20, null=True)),
                ('total_share', models.CharField(max_length=20)),
                ('share_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.ipodetails')),
            ],
        ),
        migrations.CreateModel(
            name='IpoSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qib_sub', models.CharField(max_length=20, null=True)),
                ('nii_sub', models.CharField(max_length=20, null=True)),
                ('retail_sub', models.CharField(max_length=20, null=True)),
                ('employee', models.CharField(max_length=20, null=True)),
                ('other', models.CharField(max_length=20, null=True)),
                ('total_sub', models.CharField(max_length=20)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.ipodetails')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('total_asset', models.CharField(max_length=20)),
                ('total_revenue', models.CharField(max_length=20)),
                ('profit', models.CharField(max_length=20)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_id', to='collection.ipodetails')),
            ],
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('link', models.CharField(max_length=200)),
                ('allotment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.ipodetails')),
            ],
        ),
    ]
