# Generated by Django 3.1.7 on 2021-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210309_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
