# Generated by Django 3.1.7 on 2021-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_dividenddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividenddata',
            name='dividend_fv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dividenddata',
            name='dividend_mp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
