# Generated by Django 3.1.7 on 2021-03-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210309_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividenddata',
            name='company_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
